#!/usr/bin/env python3
"""
build-critical-css.py — regenerate the inline critical CSS block in audit.html.

Run:

    python3 tools/build-critical-css.py            # serves the repo on :8935, rewrites audit.html
    python3 tools/build-critical-css.py --check    # fails (exit 1) if the block is stale

WHY THIS EXISTS
styles.css is 121KB (30KB gzipped) and it is render blocking. On a Facebook
in-app browser on mobile data that is the whole of the first second: measured
on a throttled 1.6Mbps / 150ms link, first contentful paint was 1040ms and the
first answer was not on screen until then. Every ad that points at audit.html
is paid for by the tap on that answer, and 57% of the paid visitors in the
13-18 September window left inside three seconds.

With the rules the first screen actually uses inlined in the head and the full
stylesheet loaded asynchronously behind it, the same measurement is ~330ms.

HOW IT STAYS IN SYNC
The block between the CRITICAL:BEGIN and CRITICAL:END markers in audit.html is
GENERATED. Do not hand-edit it: edit styles.css and run this script. If someone
forgets, the failure is self-healing and cosmetic rather than broken: the full
stylesheet still arrives about a second later and wins the cascade (same
specificity, later in document order), so a stale block means the first screen
paints in slightly old styles and corrects itself, not that the page breaks.
`--check` is the pre-deploy gate that catches it before a visitor does.

WHAT COUNTS AS CRITICAL
Chromium's CSS rule-usage coverage, unioned over four passes of audit.html:
390x620 with an ad hook, 320x568 (the narrow media queries), reduced motion,
and a pass where the interaction states the first screen can reach before the
full sheet lands (a chosen option, the waiting panel) are forced on so their
rules register as used. @font-face is added by hand: coverage never reports it,
and without it the first paint is in the fallback face and reflows when the
real one lands.
"""
import argparse
import http.server
import os
import re
import socketserver
import sys
import threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "<!-- CRITICAL:BEGIN (generated by tools/build-critical-css.py) -->"
END = "<!-- CRITICAL:END -->"

# The states the first screen can reach while only the inline block is applied:
# a tap that lands before the full sheet does must still turn the option blue.
FORCE = """() => {
  const b = document.querySelector('.audit-opts .qopt');
  if (b) { b.classList.add('is-on'); void b.offsetHeight; b.classList.remove('is-on'); }
  const p = document.querySelector('.audit-panel');
  if (p) { p.classList.add('is-waiting'); void p.offsetHeight; p.classList.remove('is-waiting'); }
  const n = document.createElement('p');
  n.className = 'audit-noscript audit-noscript--q';
  document.querySelector('.audit-qi').appendChild(n);
  void n.offsetHeight; n.remove();
}"""

PASSES = [
    {"w": 390, "h": 620, "camp": "leak-audit-clear-answer", "rm": None},
    {"w": 320, "h": 568, "camp": "leak-audit-plain-control", "rm": None},
    {"w": 390, "h": 620, "camp": "", "rm": "reduce"},
    {"w": 414, "h": 896, "camp": "leak-audit-why-free", "rm": None},
]

UA = ("Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 "
      "(KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBAV/470.0.0;FBDV/iPhone15,2]")


def serve(port):
    class H(http.server.SimpleHTTPRequestHandler):
        def translate_path(self, path):
            p = path.split("?", 1)[0].split("#", 1)[0].lstrip("/")
            return os.path.join(ROOT, p)

        def log_message(self, *a):
            pass

    httpd = socketserver.ThreadingTCPServer(("127.0.0.1", port), H)
    httpd.daemon_threads = True
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


def font_faces(css):
    """@font-face verbatim: coverage never reports it, and the first paint has
    to be in the real face or it reflows when the woff2 lands."""
    out = []
    for m in re.finditer(r"@font-face\s*\{[^}]*\}", css):
        out.append(m.group(0))
    return out


def collect(port):
    from playwright.sync_api import sync_playwright

    css = open(os.path.join(ROOT, "styles.css"), encoding="utf-8").read()
    ranges = {}
    with sync_playwright() as pw:
        b = pw.chromium.launch()
        for cfg in PASSES:
            kw = {"user_agent": UA, "viewport": {"width": cfg["w"], "height": cfg["h"]},
                  "is_mobile": True, "has_touch": True}
            if cfg["rm"]:
                kw["reduced_motion"] = cfg["rm"]
            c = b.new_context(**kw)
            p = c.new_page()
            # no beacons, no pixel: this is a build step, not a visit
            p.route("**/*", lambda r: r.abort()
                    if ("/api/" in r.request.url or "facebook" in r.request.url)
                    else r.continue_())
            cdp = c.new_cdp_session(p)
            cdp.send("DOM.enable")
            cdp.send("CSS.enable")
            cdp.send("CSS.startRuleUsageTracking")
            p.goto("http://127.0.0.1:%d/audit.html?utm_source=meta&utm_campaign=%s"
                   % (port, cfg["camp"]), wait_until="load")
            p.wait_for_timeout(1200)
            p.evaluate(FORCE)
            used = cdp.send("CSS.stopRuleUsageTracking")["ruleUsage"]
            texts = {}
            for r in used:
                if not r["used"]:
                    continue
                sid = r["styleSheetId"]
                if sid not in texts:
                    hdr = cdp.send("CSS.getStyleSheetText", {"styleSheetId": sid})["text"]
                    texts[sid] = hdr
                # only rules that came out of styles.css itself
                if texts[sid][r["startOffset"]:r["endOffset"]] == \
                        css[r["startOffset"]:r["endOffset"]]:
                    ranges[(r["startOffset"], r["endOffset"])] = True
            c.close()
        b.close()
    # cascade order is source order: sort by offset, never by pass
    rules = [css[a:b] for (a, b) in sorted(ranges)]
    faces = [f for f in font_faces(css) if f not in rules]
    return "\n".join(faces + rules)


def block(crit):
    return (BEGIN + "\n"
            "  <!-- The first screen's own rules, inlined so the question paints with\n"
            "       the document instead of a round trip later. Everything else follows\n"
            "       in styles.css, loaded without blocking the paint and applied when it\n"
            "       lands. GENERATED: edit styles.css, then run\n"
            "       python3 tools/build-critical-css.py -->\n"
            "  <style>" + crit + "</style>\n  " + END)


def current(html):
    i = html.find(BEGIN)
    j = html.find(END)
    if i == -1 or j == -1:
        return None
    return html[i:j + len(END)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8935)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    path = os.path.join(ROOT, "audit.html")
    html = open(path, encoding="utf-8").read()
    if current(html) is None:
        print("audit.html has no CRITICAL:BEGIN/END markers — nothing to write into.")
        return 2

    httpd = serve(args.port)
    try:
        crit = collect(args.port)
    finally:
        httpd.shutdown()

    fresh = block(crit)
    if current(html) == fresh:
        print("critical CSS is current (%d bytes)." % len(crit))
        return 0
    if args.check:
        print("STALE: audit.html's critical CSS no longer matches styles.css. "
              "Run: python3 tools/build-critical-css.py")
        return 1
    open(path, "w", encoding="utf-8").write(html.replace(current(html), fresh))
    print("wrote %d bytes of critical CSS into audit.html" % len(crit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
