#!/usr/bin/env python3
"""
build-critical-css.py — regenerate the inline critical CSS block in audit.html.

Run:

    python3 tools/build-critical-css.py            # serves the repo on :8935, rewrites audit.html
    python3 tools/build-critical-css.py --check    # fails (exit 1) if the block is stale

WHY THIS EXISTS
styles.css is 121KB (30KB gzipped) and it is render blocking. On a Facebook
in-app browser on mobile data that is the whole of the first second: measured
on a throttled 1.6Mbps / 150ms link, first contentful paint was 1040ms and the
first answer was not on screen until then. Every ad that points at audit.html
is paid for by the tap on that answer, and 57% of the paid visitors in the
13-18 September window left inside three seconds.

With the rules the first screen actually uses inlined in the head and the full
stylesheet loaded asynchronously behind it, the same measurement is ~330ms.

HOW IT STAYS IN SYNC
The block between the CRITICAL:BEGIN and CRITICAL:END markers in audit.html is
GENERATED. Do not hand-edit it: edit styles.css and run this script. If someone
forgets, the failure is self-healing and cosmetic rather than broken: the full
stylesheet still arrives about a second later and wins the cascade (same
specificity, later in document order), so a stale block means the first screen
paints in slightly old styles and corrects itself, not that the page breaks.
`--check` is the pre-deploy gate that catches it before a visitor does.

WHAT COUNTS AS CRITICAL
Chromium's CSS rule-usage coverage, unioned over four passes of audit.html:
390x620 with an ad hook, 320x568 (the narrow media queries), reduced motion,
and a pass where the interaction states the first screen can reach before the
full sheet lands (a chosen option, the waiting panel) are forced on so their
rules register as used. @font-face is added by hand: coverage never reports it,
and without it the first paint is in the fallback face and reflows when the
real one lands.
"""
import argparse
import http.server
import os
import re
import socketserver
import sys
import threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BEGIN = "<!-- CRITICAL:BEGIN (generated by tools/build-critical-css.py) -->"
END = "<!-- CRITICAL:END -->"

# The states the first screen can reach while only the inline block is applied:
# a tap that lands before the full sheet does must still turn the option blue.
FORCE = """() => {
  const b = document.querySelector('.audit-opts .qopt');
  if (b) { b.classList.add('is-on'); void b.offsetHeight; b.classList.remove('is-on'); }
  const p = document.querySelector('.audit-panel');
  if (p) { p.classList.add('is-waiting'); void p.offsetHeight; p.classList.remove('is-waiting'); }
  const n = document.createElement('p');
  n.className = 'audit-noscript audit-noscript--q';
  document.querySelector('.audit-qi').appendChild(n);
  void n.offsetHeight; n.remove();
}"""

PASSES = [
    {"w": 390, "h": 620, "camp": "leak-audit-clear-answer", "rm": None},
    {"w": 320, "h": 568, "camp": "leak-audit-plain-control", "rm": None},
    {"w": 390, "h": 620, "camp": "", "rm": "reduce"},
    {"w": 414, "h": 896, "camp": "leak-audit-why-free", "rm": None},
]

UA = ("Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 "
      "(KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBAV/470.0.0;FBDV/iPhone15,2]")


def serve(port):
    class H(http.server.SimpleHTTPRequestHandler):
        def translate_path(self, path):
            p = path.split("?", 1)[0].split("#", 1)[0].lstrip("/")
            return os.path.join(ROOT, p)

        def log_message(self, *a):
            pass

    socketserver.ThreadingTCPServer.allow_reuse_address = True
    httpd = socketserver.ThreadingTCPServer(("127.0.0.1", port), H)
    httpd.daemon_threads = True
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


def font_faces(css):
    """@font-face verbatim: coverage never reports it, and the first paint has
    to be in the real face or it reflows when the woff2 lands."""
    out = []
    for m in re.finditer(r"@font-face\s*\{[^}]*\}", css):
        out.append(m.group(0))
    return out


CONDITIONAL = ("@media", "@supports", "@container", "@layer")


def at_blocks(css):
    """Every conditional at-rule block in the sheet as (prelude, body_start, body_end).

    Coverage reports the style rules INSIDE an @media block (and the bare condition
    text) but never the `@media … {` and `}` around them. Emitting those slices as
    they come ships `(max-width: 960px)` as a stray line: the rule after it is
    swallowed as a bad selector and the rest of the block applies at every width.
    That went live once. This index is how a used rule finds its wrapper again.
    """
    out, stack, seg, i, n = [], [], 0, 0, len(css)
    while i < n:
        ch = css[i]
        if ch == "/" and css[i:i + 2] == "/*":
            j = css.find("*/", i + 2)
            i = n if j == -1 else j + 2
            continue
        if ch in "\"'":
            j = i + 1
            while j < n and css[j] != ch:
                j += 2 if css[j] == "\\" else 1
            i = j + 1
            continue
        if ch == "{":
            prelude = re.sub(r"/\*.*?\*/", "", css[seg:i], flags=re.S).strip()
            stack.append((prelude, i + 1))
            seg = i + 1
        elif ch == "}":
            if stack:
                prelude, start = stack.pop()
                if prelude.startswith(CONDITIONAL):
                    out.append((" ".join(prelude.split()), start, i))
            seg = i + 1
        elif ch == ";":
            seg = i + 1
        i += 1
    return out


def wrap(css, ranges):
    """Used rules in source order, each back inside the at-rules it was written in."""
    blocks = at_blocks(css)
    out, open_ctx = [], ()

    def close(to):
        nonlocal open_ctx
        while open_ctx != to[:len(open_ctx)] or len(open_ctx) > len(to):
            out.append("}")
            open_ctx = open_ctx[:-1]

    for a, b in sorted(ranges):
        text = css[a:b]
        if "{" not in text:
            continue                      # a bare condition: coverage's, not a rule
        ctx = tuple(p for (p, s, e) in sorted(blocks, key=lambda t: t[1])
                    if s <= a and b <= e)
        close(ctx)
        for p in ctx[len(open_ctx):]:
            out.append(p + " {")
        open_ctx = ctx
        out.append(text)
    close(())
    return out


def lint(crit):
    """Refuse to write a block that would misparse. Returns a list of problems."""
    bad = []
    body = re.sub(r"/\*.*?\*/", "", crit, flags=re.S)
    for ln in body.splitlines():
        if re.match(r"^\s*(not\s+|only\s+)?(screen\s+and\s+|print\s+and\s+)?\([^{};]*\)\s*$", ln):
            bad.append("bare media condition: %r" % ln.strip())
    if body.count("{") != body.count("}"):
        bad.append("unbalanced braces: %d open, %d close" % (body.count("{"), body.count("}")))
    if "</style" in body.lower():
        bad.append("a literal </style> would end the inline block early")
    return bad


def collect(port):
    from playwright.sync_api import sync_playwright

    css = open(os.path.join(ROOT, "styles.css"), encoding="utf-8").read()
    ranges = {}
    with sync_playwright() as pw:
        b = pw.chromium.launch()
        for cfg in PASSES:
            kw = {"user_agent": UA, "viewport": {"width": cfg["w"], "height": cfg["h"]},
                  "is_mobile": True, "has_touch": True}
            if cfg["rm"]:
                kw["reduced_motion"] = cfg["rm"]
            c = b.new_context(**kw)
            p = c.new_page()
            # no beacons, no pixel: this is a build step, not a visit
            p.route("**/*", lambda r: r.abort()
                    if ("/api/" in r.request.url or "facebook" in r.request.url)
                    else r.continue_())
            cdp = c.new_cdp_session(p)
            cdp.send("DOM.enable")
            cdp.send("CSS.enable")
            cdp.send("CSS.startRuleUsageTracking")
            p.goto("http://127.0.0.1:%d/audit.html?utm_source=meta&utm_campaign=%s"
                   % (port, cfg["camp"]), wait_until="load")
            p.wait_for_timeout(1200)
            p.evaluate(FORCE)
            used = cdp.send("CSS.stopRuleUsageTracking")["ruleUsage"]
            texts = {}
            for r in used:
                if not r["used"]:
                    continue
                sid = r["styleSheetId"]
                if sid not in texts:
                    hdr = cdp.send("CSS.getStyleSheetText", {"styleSheetId": sid})["text"]
                    texts[sid] = hdr
                # only rules that came out of styles.css itself
                if texts[sid][r["startOffset"]:r["endOffset"]] == \
                        css[r["startOffset"]:r["endOffset"]]:
                    ranges[(r["startOffset"], r["endOffset"])] = True
            c.close()
        b.close()
    # cascade order is source order: sort by offset, never by pass
    rules = wrap(css, ranges)
    faces = [f for f in font_faces(css) if f not in rules]
    return "\n".join(faces + rules)


def block(crit):
    return (BEGIN + "\n"
            "  <!-- The first screen's own rules, inlined so the question paints with\n"
            "       the document instead of a round trip later. Everything else follows\n"
            "       in styles.css, loaded without blocking the paint and applied when it\n"
            "       lands. GENERATED: edit styles.css, then run\n"
            "       python3 tools/build-critical-css.py -->\n"
            "  <style>" + crit + "</style>\n  " + END)


def current(html):
    i = html.find(BEGIN)
    j = html.find(END)
    if i == -1 or j == -1:
        return None
    return html[i:j + len(END)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8935)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    path = os.path.join(ROOT, "audit.html")
    html = open(path, encoding="utf-8").read()
    if current(html) is None:
        print("audit.html has no CRITICAL:BEGIN/END markers — nothing to write into.")
        return 2

    httpd = serve(args.port)
    try:
        crit = collect(args.port)
    finally:
        httpd.shutdown()
        httpd.server_close()

    problems = lint(crit)
    if problems:
        print("REFUSING to write: the generated block would misparse.")
        for p in problems:
            print("  - " + p)
        return 3

    fresh = block(crit)
    if current(html) == fresh:
        print("critical CSS is current (%d bytes)." % len(crit))
        return 0
    if args.check:
        print("STALE: audit.html's critical CSS no longer matches styles.css. "
              "Run: python3 tools/build-critical-css.py")
        return 1
    open(path, "w", encoding="utf-8").write(html.replace(current(html), fresh))
    print("wrote %d bytes of critical CSS into audit.html" % len(crit))
    return 0


if __name__ == "__main__":
    sys.exit(main())
